FROM debian:latest

RUN apt-get update && apt-get -y upgrade

RUN apt-get -y install sudo\
                    unzip\
                    wget\
                    net-tools\
                    ufw\
                    git

RUN apt-get -y update
RUN apt-get -y upgrade

RUN     apt-get -y install python3\
                        python3-pip

RUN     pip3 -y install discord\
                    discord.py\
                    embed\
                    asyncio

COPY    discord.py .

CMD ["python3","discord.py"]