FROM debian:latest

RUN apt-get update && apt-get -y upgrade

RUN apt-get -y install sudo\
                    unzip\
                    wget\
                    net-tools\
                    ufw\
                    git\
                    npm

RUN apt-get -y update
RUN apt-get -y upgrade

RUN     apt-get -y install  python3\
                        python3-pip

RUN     python3 -m pip install -U discord.py
RUN     python3 -m pip install -U "discord.py [voice]"


COPY    app.py .

CMD ["python3","app.py"]