FROM debian:latest
RUN apt-get -y update
RUN apt-get -y upgrade

# 기본 프로그램
RUN apt-get -y install sudo
RUN apt-get -y install git

RUN apt-get -y update
RUN apt-get -y upgrade

RUN     apt-get -y install python3
RUN     apt-get -y install python3-pip

RUN     pip3 install discord\
                    discord.py\
                    embed\
                    asyncio\
                    random

COPY 1.sh .
RUN sh 1.sh

RUN     apt-get update

COPY    discord.py .
RUN     apt-get update

CMD ["python3","discord.py"]