FROM debian:latest
RUN apt-get -y update
RUN apt-get -y upgrade

# 기본 프로그램
RUN apt-get -y install sudo
RUN apt-get -y install git

RUN apt-get -y update
RUN apt-get -y upgrade

RUN     apt-get -y install python3
RUN     apt-get -y install python3-pip
RUN     apt-get -y install python
RUN     apt-get -y install python-pip

RUN     pip3 install discord\
                    discord.py\
                    embed\
                    asyncio

RUN     python3 -m pip install discord\
                    discord.py
# RUN     pip install random

COPY 1.sh .
RUN sh 1.sh

COPY    discord.py .

CMD ["python3","discord.py"]